<?php

/**
 * @file
 * Functions to support theming in the <%= themeNameMachine %> theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function <%= themeNameMachine %>_preprocess_html(array &$variables) {

}

/**
 * Implements hook_preprocess_page() for page.html.twig.
 */
function <%= themeNameMachine %>_preprocess_page(array &$variables) {

}

/**
 * Implements hook_preprocess_form().
 */
function <%= themeNameMachine %>_preprocess_form(array &$variables) {

}
